# Generated by Django 4.1.4 on 2023-01-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_u_name', models.CharField(max_length=20)),
                ('m_email', models.CharField(max_length=30)),
                ('u_message', models.TextField()),
            ],
        ),
    ]
