# Generated by Django 4.1.4 on 2023-01-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_desc', models.TextField()),
                ('movie_full', models.FileField(upload_to='')),
                ('movie_thumb', models.FileField(upload_to='')),
                ('movie_issu_date', models.TimeField()),
            ],
        ),
    ]
