# Generated by Django 4.1.4 on 2023-01-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_issu_date',
            field=models.DateTimeField(),
        ),
    ]
