# Generated by Django 4.1.4 on 2023-01-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movie', '0005_alter_movie_movie_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_full',
            field=models.FileField(upload_to='video'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_thumb',
            field=models.FileField(upload_to='image'),
        ),
    ]
