# Generated by Django 4.1.4 on 2023-01-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movie', '0006_alter_movie_movie_full_alter_movie_movie_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_thumb',
            field=models.ImageField(upload_to='image'),
        ),
    ]
